import Provider from "@/components/Provider";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "@/utils/ThemeProvider";
import Background from "@/components/Background";

export const metadata = {
  title: "3d AI Avatar",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`h-screen w-full dark`}>

      <Provider>
      <Background/>
      <div  className={`grid grid-rows-[auto_1fr] h-screen w-full text-black dark:text-white min-h-screen`}>
        <Navbar/>
        <div className="h-full overflow-y-scroll">
          {children}
        </div>
      </div>
        
      </Provider>
      </body>
    </html>
  );
}
