import "./globals.css";
import Navbar from "@/components/Navbar";
import NextAuthSessionProviders from "@/providers/NextAuthSessionProviders";

export const metadata = {
  title: "3d AI Avatar",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body 
        className={`dark grid grid-rows-[auto_1fr] h-[100dvh] w-full bg-zinc-950 text-white min-h-screen bg-gradient-to-r from-slate-500 to-slate-800`}
      >
      
      <NextAuthSessionProviders>
        
        <Navbar/>
        <div className="h-full max-h-full overflow-y-scroll">
          {children}
        </div>
        
      </NextAuthSessionProviders>
      
      </body>
    </html>
  );
}
